1. Fixed user being able to submit transportation claim through "Claims"
TA-Software/Payroll pull request #152
Opened 2022-10-25 11:31 UTC by CoreVisional

2. Update .gitignore to ignore vscode files

2022-11-12 07:39 UTC, ErwinSuwito requested changes

2022-11-12 07:39 UTC, ErwinSuwito commented on Payroll.Web/Controllers/ClaimsController.cs
> +            if (!ModelState.IsValid && claim.ClaimType.Equals(claimTypeValues) && claim.File != null)
`claim.ClaimType.Equals(claimTypeValues)` will always return false as you're comparing an enum with an array of enum. A better way is to use switch to check which claim type is allowed to be submitted through this form. (Though there are none at the moment)

2022-11-14 04:11 UTC, CoreVisional commented on Payroll.Web/Controllers/ClaimsController.cs
> +            if (!ModelState.IsValid && claim.ClaimType.Equals(claimTypeValues) && claim.File != null)
Refactored the code to use switch-case for claim.ClaimType check. Thanks for the clarification regarding the returning value for the equality check against an enum with an array of enum also.

2022-11-14 04:25 UTC, CoreVisional reviewed
Please kindly disregard commit "db119a" as it showed that I already committed the claim.ClaimType changes only to discover upon restarting my VS that it committed the incorrect changes.

2022-11-14 07:20 UTC, ErwinSuwito commented on Payroll.Web/Controllers/ClaimsController.cs
> +            if (!ModelState.IsValid && claim.ClaimType.Equals(claimTypeValues) && claim.File != null)
What I meant is to remove `claim.ClaimType.Equals(claimTypeValues)` from the if conditions, then put the switch inside the if body

2022-11-15 05:58 UTC, CoreVisional commented on Payroll.Web/Controllers/ClaimsController.cs
> +            if (!ModelState.IsValid && claim.ClaimType.Equals(claimTypeValues) && claim.File != null)
Updated the if body with the switch case statement on commit "f054d57".

2022-11-16 08:19 UTC, CoreVisional commented on Payroll.Web/Controllers/ClaimsController.cs
> +            if (!ModelState.IsValid && claim.ClaimType.Equals(claimTypeValues) && claim.File != null)
Updated claim.ClaimType check on commit "06ed64b".

2022-11-17 08:03 UTC, ErwinSuwito approved these changes

2022-11-17 08:03 UTC, merged